#!/usr/bin/env python

import sys
from sys import path
from pprint import pformat

path.append("../python")

classPath = {
    'cli' : 'hydra.lib.cli.cli',
    'zmq' : 'hydra.zmqtest.runtest.RunTest',
    'zmqrate': 'hydra.zmqtest.maxrate_test.Run',
    'zmqdrop': 'hydra.zmqtest.pktdrop_test.Run',
    'zmqfixed': 'hydra.zmqtest.fixed_test.Run',
    'zmq-pub' : 'hydra.zmqtest.zmq_pub.run',
    'zmq-sub' : 'hydra.zmqtest.zmq_sub.run',
    'rmq' : 'hydra.rmqtest.runtest.RunTest',
    'rmqpub' : 'hydra.rmqtest.rmq_pub.run',
    'rmqfixed': 'hydra.rmqtest.fixed_test.run',
    'hw': 'hydra.helloworldtest.runtest.RunTest',
    'kafka': 'hydra.kafkatest.runtest.RunTest',
    'kafkapub': 'hydra.kafkatest.kafka_pub.run',
    'kafkasub': 'hydra.kafkatest.kafka_sub.run',
    'kafkafixed': 'hydra.kafkatest.fixed_test.run',
    'kafkarate': 'hydra.kafkatest.maxrate_test.Run',
    'kafka-batch': 'hydra.kafkatest.batchsize_test.Run',
}
if len(sys.argv) < 2 or sys.argv[1] == '-h' or sys.argv[1] == '--help':
    print("Options are %s " % sys.argv[0] + " " + pformat(classPath.keys()))
    sys.exit(1)
arg1 = sys.argv[1]
if arg1 in classPath.keys():
    arg1 = classPath[arg1]
dFuncPath = (arg1).split('.')
dModule = '.'.join(dFuncPath[0:-1])
dFunc = dFuncPath[-1]

iFunc = getattr(__import__(dModule, fromlist=[dFunc]), dFunc)

if '__main__' == __name__:
    argv = sys.argv
    print ("Running command : " + argv[0] + ' ' + '.'.join(argv[1:]))
    del argv[1]
    exit(iFunc(argv))

