#!/usr/bin/env python

import sys
from sys import path
path.append("../python")

classPath = {
    'cli' : 'hydra.lib.cli.cli',
    'zmq' : 'hydra.zmqtest.runtest.RunTest',
    'zmqsuit': 'hydra.zmqtest.runtestsuit.RunSuit',
    'zmqrate': 'hydra.zmqtest.maxrate_test.Run',
    'zmqdrop': 'hydra.zmqtest.runtestsuit.RunSuitPacketDrop',
    'zmqfixed': 'hydra.zmqtest.fixed_test.Run',
    'zmq-pub' : 'hydra.zmqtest.zmq_pub.run',
    'zmq-sub' : 'hydra.zmqtest.zmq_sub.run',
}
arg1 = sys.argv[1]
if arg1 in classPath.keys():
    arg1 = classPath[arg1]
dFuncPath = (arg1).split('.')
dModule = '.'.join(dFuncPath[0:-1])
dFunc = dFuncPath[-1]

iFunc = getattr(__import__(dModule, fromlist=[dFunc]), dFunc)

if '__main__' == __name__:
    argv = sys.argv
    print ("Running command : " + argv[0] + ' ' + '.'.join(argv[1:]))
    del argv[1]
    exit(iFunc(argv))

