#!/usr/bin/env python
# -*- coding: utf-8 -*-
from sys import path
path.append("src/main/python")
from mScaleZMQ.zmq_pub_sub import zmq_sub

def main():
    zmq_sub()

if '__main__' == __name__:
    main()
