#!/usr/bin/env python
# -*- coding: utf-8 -*-
from sys import path
path.append("src/main/python")
from mScale.zmqTest.zmq_pub_sub import zmq_pub

def main():
    zmq_pub()

if '__main__' == __name__:
    main()
