#!/usr/bin/env python

import sys
from sys import path
path.append("../python")

dFuncPath = (sys.argv[1]).split('.')
dModule = '.'.join(dFuncPath[0:-1])
dFunc = dFuncPath[-1]

iFunc = getattr(__import__(dModule, fromlist=[dFunc]), dFunc)

if '__main__' == __name__:
    argv = sys.argv
    print ("Running command : " + '.'.join(argv))
    del argv[1]
    exit(iFunc(argv))

